version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run:
          name: Build
          command: |
            cargo build
            cargo clippy -- -D warnings

workflows:
  build:
    jobs:
      - build
